### ISSUE TITLE
`fsl` dependent on `plugins.yaml`

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/fishsense-lite-cli#17]
```
~/workspace/e4e/fishsense/2024-09-23$ fsl --help
Traceback (most recent call last):
  File "/home/dronelab/workspace/e4e/fishsense/fishsense-lite/.venv/bin/fsl", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dronelab/workspace/e4e/fishsense/fishsense-lite/fishsense_lite/run.py", line 10, in main
    cli = Cli("./fishsense_lite/plugins.yaml", prog="fishsense-lite")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dronelab/workspace/e4e/fishsense/fishsense-lite/.venv/lib/python3.11/site-packages/bom_common/pluggable_cli/cli.py", line 21, in __init__
    with plugins_yaml_path.open("r", encoding="utf8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dronelab/.pyenv/versions/3.11.9/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'fishsense_lite/plugins.yaml'
```

**Comment by ccrutchf** [comment]
Fixed
